### PR TITLE
Update dependencies to original source

### PR DESCRIPTION
**Pull request by diecav**
Update golang version and other dependencies to avoid security issues

### CODE REVIEW

**Comment by diecav** [comment]
Hi guys,
do you think is possible to merge the changes done by @LHozzan so that we finally have a new updated version on docker hub?

**Comment by LHozzan** [comment]
Hi @diecav .

Thanks to `Dockerfile` you can release your own copy of image and upload, where you wish.
You read [this comment](https://github.com/alxrem/prometheus-logstash-exporter/pull/25#issuecomment-1167857874), right?

**Comment by diecav** [comment]
Hi @LHozzan,
yes i can also solve it this way ;-) 

I'm a bit surprised that in general there aren't officially maintained logstash exporter. I've fund others but with outdated commits...

Thank you
Best

**Comment by diecav** [comment]
Pull request can be closed

**Comment by LHozzan** [comment]
> I'm a bit surprised that in general there aren't officially maintained logstash exporter. I've fund others but with outdated commits...

Unfortunately, you have right :(. This exporter from Alex is by my humble opinion, best solution. This is reason, why I want to maintain it and my second motivation is, that we use it in our logging helm chart :).

In Elastic community [was effort](https://discuss.elastic.co/t/how-to-monitor-the-beats-using-prometheus/275394) to add Prometheus metrics endpoint on existing Logstash metric endpoint, but basically, guys from Elastic have his own monitoring solution and supporting they direct "rival" not have sense for them :(.

There is also [Prometheus json exporter](https://github.com/prometheus-community/json_exporter), but I not have tested it yet.

There is also chance, that I can ask SAP for some resources and made some miracle for automatic build, but ... It is more easy for me just provide `Dockerfile` and let for anybody build his own image ;).

If more guys come with same request about official DockerHub Image, I will get more motivation for my chiefs to support open source comunity ;).

**Pull request closed without merging**
